name: testproject
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  lottie : ^1.2.1
  flutter_slidable: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_heatmap_calendar: ^1.0.5
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.0.0
  firebase_database: ^10.0.6
  firebase_core: ^2.3.0
  font_awesome_flutter: ^10.3.0
  url_launcher: ^6.1.7
  http: ^0.13.5
  provider: ^6.0.3
  readmore: ^2.2.0
  flutter_svg: ^1.1.6
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  google_nav_bar: ^5.0.6
  hive_generator: ^2.0.0
  build_runner: ^2.3.2

  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/rrr.jpg
    - images/b.jpg
    - images/cover.jpg
    - images/logo.png
    - images/list.png
    - images/bookcase.png
    - images/books/1.1.jpg
    - images/books/1.jpg
    - images/books/2.1.jpg
    - images/books/2.jpg
    - images/books/3.1.jpg
    - images/books/3.jpg
    - images/books/4.1.jpg
    - images/books/4.jpg
    - images/books/5.jpg
    - images/books/6.jpg
    - images/books/7.jpg
    - images/books/8.jpg
    - images/bookim/10.jpg
    - images/bookim/11.jpg
    - images/bookim/12.jpg
    - images/bookim/13.jpg
    - images/bookim/14.jpg
    - images/bookim/15.jpg
    - images/bookim/16.jpg
    - images/bookim/17.jpg
    - images/bookim/18.jpg
    - images/bookim/19.jpg
    - images/bookim/20.jpg
    - images/bookim/21.jpg
    - images/bookim/22.jpg
    - images/bookim/23.jpg
    - images/bookim/24.jpg
    - images/bookim/25.jpg
    - images/bookim/26.jpg
    - images/bookim/27.jpg
    - images/bookim/28.jpg
    - images/bookim/29.jpg
    - images/bookim/30.jpg
    - images/bookim/31.jpg
    - images/bookim/32.jpg
    - images/bookim/33.jpg
    - images/bookim/34.jpg
    - images/bookim/35.jpg
    - images/bookim/36.jpg
    - images/bookim/37.jpg
    - images/bookim/38.jpg
    - images/bookim/39.jpg
    - images/bookim/40.jpg
    - images/bookim/41.jpg
    - images/bookim/42.jpg
    - images/bookim/43.jpg
    - images/bookim/44.jpg
    - images/bookim/45.jpg
    - images/bookim/46.jpg
    - images/bookim/47.jpg
    - images/bookim/48.jpg
    - images/bookim/49.jpg
    - images/bookim/50.jpg
    - images/bookim/51.jpg
    - images/bookim/52.jpg
    - images/bookim/53.jpg
    - images/bookim/54.jpg
    - images/bookim/55.jpg
    - images/bookim/56.jpg
    - images/bookim/57.jpg
    - images/bookim/58.jpg
    - images/bookim/59.jpg
    - images/bookim/60.jpg
    - images/bookim/61.jpg
    - images/bookim/62.jpg
    - images/bookim/63.jpg
    - images/bookim/64.jpg
    - images/bookim/65.jpg
    - images/bookim/66.jpg
    - images/bookim/67.jpg
    - images/bookim/68.jpg
    - images/bookim/69.jpg
    - images/bookim/70.jpg
    - images/bookim/71.jpg
    - images/bookim/72.jpg
    - images/bookim/73.jpg
    - images/bookim/74.jpg
    - images/authimg/80.jpg
    - images/authimg/81.jpg
    - images/authimg/82.jpg
    - images/authimg/84.jpg
    - images/authimg/85.jpg
    - images/authimg/86.jpg
    - images/authimg/87.jpg
    - images/authimg/88.jpg
    - images/authimg/89.jpg
    - images/authimg/90.jpg
    - images/authimg/91.jpg
    - images/authimg/92.jpg
    - images/authimg/93.jpg
    - images/authimg/94.jpg
    - images/authimg/95.jpg
    - images/authimg/96.jpg
    - images/authimg/97.jpg
    - images/authimg/98.jpg





    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
